"use server";

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

export async function updateEventLocation(eventId: string, locationName: string) {
  const session = await getServerSession(authOptions);
  
  if (!session?.user?.id) {
    throw new Error("Unauthorized");
  }

  // Optional: verify the user is the captain of a group in this event
  const event = await prisma.event.findUnique({
    where: { id: eventId },
    include: { groups: true }
  });

  if (!event) throw new Error("Event not found");

  const isCaptain = event.groups.some(g => g.captainId === session.user.id);
  if (!isCaptain) throw new Error("Only the captain can update the location");

  await prisma.event.update({
    where: { id: eventId },
    data: { locationName }
  });

  revalidatePath(`/events/${eventId}`);
  return { success: true };
}

export async function createManualEvent(formData: FormData) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    throw new Error("Unauthorized");
  }

  const title = formData.get("title") as string;
  const sportName = formData.get("sportName") as string;
  const locationName = formData.get("locationName") as string;
  const scheduledTime = formData.get("scheduledTime") as string;

  if (!title || !sportName || !locationName || !scheduledTime) {
    throw new Error("Missing required fields");
  }

  const event = await prisma.event.create({
    data: {
      title,
      sportName,
      locationName,
      locationLat: 0, // Placeholder
      locationLng: 0, // Placeholder
      scheduledTime: new Date(scheduledTime),
      status: "Scheduled",
      groups: {
        create: {
          isAutoGenerated: false,
          captainId: session.user.id,
          members: {
            create: {
              userId: session.user.id,
            },
          },
        },
      },
    },
  });

  revalidatePath("/dashboard");
  return { id: event.id };
}

