"use server";

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";

const SPORT_THRESHOLDS: Record<string, number> = {
  Tennis:     2,  // doubles
  Padel:      2,  // doubles
  Football:   4,  // mini-pitch / pickup
  Basketball: 4,  // half-court 2v2
  Volleyball: 4,  // 2v2 beach
  Running:    2,  // pair run
  Swimming:   2,
  Default:    2,
};

export async function generateMatches() {
  // 1. Find all users where availableToday == true, including sport preferences
  const availableUsers = await prisma.user.findMany({
    where: { availableToday: true },
    include: { sportPreferences: true }
  });

  if (availableUsers.length === 0) return { message: "No users available today.", count: 0 };

  // 2. Group these users based on their shared SportPreference
  const groupedUsers: Record<string, typeof availableUsers> = {};

  availableUsers.forEach(user => {
    user.sportPreferences.forEach(pref => {
      const sport = pref.sportName;
      if (!groupedUsers[sport]) {
        groupedUsers[sport] = [];
      }
      groupedUsers[sport].push(user);
    });
  });

  const matchesCreated = [];

  // 3. If a sport has enough available users, create Event, Group, and GroupMember records
  for (const [sport, users] of Object.entries(groupedUsers)) {
    // Basic deduplication in case a user has duplicate sport preferences
    const uniqueUsers = Array.from(new Map(users.map(u => [u.id, u])).values());
    
    const threshold = SPORT_THRESHOLDS[sport] || SPORT_THRESHOLDS.Default;

    if (uniqueUsers.length >= threshold) {
      let i = 0;
      // Create as many matches as possible for this sport
      while (i + threshold <= uniqueUsers.length) {
        const matchUsers = uniqueUsers.slice(i, i + threshold);
        i += threshold;

        // 4. Randomly assign one user as captainId
        const captainIndex = Math.floor(Math.random() * matchUsers.length);
        const captainId = matchUsers[captainIndex].id;

        const event = await prisma.event.create({
          data: {
            title: `${sport} Match`,
            sportName: sport,
            locationName: "Central Park (Auto-assigned)",
            locationLat: 40.7812,
            locationLng: -73.9665,
            scheduledTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow
            status: "Scheduled",
            groups: {
              create: {
                isAutoGenerated: true,
                captainId: captainId,
                members: {
                  create: matchUsers.map(u => ({
                    userId: u.id
                  }))
                }
              }
            }
          }
        });

        matchesCreated.push({ eventId: event.id, sport });
      }
    }
  }

  revalidatePath("/dashboard");
  return { message: `Created ${matchesCreated.length} matches.`, count: matchesCreated.length, matchesCreated };
}
